### ISSUE TITLE
Error: tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'index_type' in NodeDef:

### ISSUE THREAD

**Issue by rohith14** [yeephycho/tensorflow-face-detection#22]
While using the frozen_inference_graph_face.pb to convert into tensorRT optimized graph, I am running into this issue

## Error
2018-05-04 10:20:52.305790: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 1
Traceback (most recent call last):
  File "test_TF_TensorRT_Prediction_GPU.py", line 189, in <module>
    precision_mode="FP32")  # Get optimized graph
  File "/local/Anaconda3/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 115, in create_inference_graph
    int(msg[0]))
tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'index_type' in NodeDef:
	 [[Node: MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/ones = Fill[T=DT_INT32](MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/Reshape, MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/ones/Const)]]
	 [[Node: MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/ones = Fill[T=DT_INT32](MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/Reshape, MultipleGridAnchorGenerator/Meshgrid_17/ExpandedShape_1/ones/Const)]]
(tensorflow_gpu_r1.7) [rbakkann@rbakkann-deep-deb8-64:/local/del/tftrt]

**Comment by yeephycho** [comment]
I'm also interested in trt, if you have any progress, please let me know!
